service: ffx-index-frontend

provider:
  name: aws
  runtime: nodejs8.10
  profile: kieran

functions:
  server:
    handler: handler.server
    memorySize: 128
    events:
      - http:
          path: /{proxy+}
          method: get

plugins:
  - serverless-offline
